# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.


trigger:
- none

pool: default

steps:
    - task: NodeTool@0
      displayName: 'install node'
      inputs:
          versionSource: 'spec'
          versionSpec: '6.x'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
        MaxArtifactSize: 200mb
        StoreAsTar: true

    - script: |
        npm pack
        npm start
      displayName: 'run program'
