# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.


trigger:
- none

pool: default

steps:
    - task: NodeTool@0
      inputs:
        versionSource: 'spec'
        versionSpec: '10.19.0'
        checkLatest: true
    - task: Npm@1
      inputs:
        command: 'install'
        workingDir: './'
        verbose: true
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
    - task: Npm@1
      inputs:
        command: 'publish'
        verbose: true
        publishRegistry: 'useFeed'
        publishFeed: 'e04d6ea5-70c3-48d9-8aab-24717f6fb3f9/52c3fd2f-74d3-439b-b77e-832cde4114b2'
    # - script: |
    #     npm config list
    #     npm cache clean --force

      # displayName: 'run program'
