# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.


trigger:
- none

pool: default

steps:
    - task: NodeTool@0
      inputs:
        versionSource: 'spec'
        versionSpec: '6.x'
        checkLatest: true
    
    - task: Npm@1
      inputs:
        command: 'publish'
        publishRegistry: 'useFeed'
        publishFeed: '956c82df-33a9-435f-a642-15192b42f895'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
    # - script: |
    #     npm config list
    #     npm cache clean --force

      displayName: 'run program'
