# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.


trigger:
- none

pool: default
variables:
  majorVersion: 1
  minorVersion: $[counter(variables['majorVersion'], 0)]
  patchVersion: $[counter(format('{0}.{1}', variables['majorVersion'], variables['minorVersion']), 0)]
  versionNumber: '$(majorVersion).$(minorVersion).$(patchVersion)'

steps:
    - task: NodeTool@0
      inputs:
        versionSource: 'spec'
        versionSpec: '10.19.0'
        checkLatest: true
    - task: Npm@1
      inputs:
        command: 'install'
        workingDir: './'
        verbose: true
    - task: Bash@3
      displayName: 'Update Version'
      inputs:
        targetType: 'inline'
        script: |
          echo "Current Version: $(versionNumber)"
          npm --no-git-tag-version version $(versionNumber)
    
    - task: PublishBuildArtifacts@1
      inputs:
         PathtoPublish: '$(Build.ArtifactStagingDirectory)'
         ArtifactName: 'drop'
         publishLocation: 'Container'
         StoreAsTar: true
         
       
    - task: Npm@1
      inputs:
        command: 'publish'
        verbose: true
        publishRegistry: 'useFeed'
        publishFeed: 'e04d6ea5-70c3-48d9-8aab-24717f6fb3f9/52c3fd2f-74d3-439b-b77e-832cde4114b2'
    # - script: |
    #     npm config list
    #     npm cache clean --force

      # displayName: 'run program'
